### ISSUE TITLE
Controls always move player two lanes over

### ISSUE THREAD

**Issue by markmelvin** [wmcnamara/speedcube#3]
Cool game!  But I find it almost impossible to play as I cannot move the player one lane at a time. It seems the player always moves two lanes at once, making it impossible to avoid obstacles. Is this desired behavior?

I'm running it on Windows 10.

**Comment by wmcnamara** [comment]
Do you know which commit/version you're on?

**Comment by wmcnamara** [comment]
If you downloaded from the release can you provide me with some steps to reproduce it? Seems to work fine on my end.

Also, there are only 3 lanes. Left middle and right. Just to clarify

**Comment by wmcnamara** [comment]
Also, if you could provide a video or GIF that describes the problem, that could be very helpful aswell.

**Comment by markmelvin** [comment]
> Also, there are only 3 lanes. Left middle and right. Just to clarify

Ah! Maybe I'm just not very good at it then! It looked like there were more lanes based on the number of obstacles, but maybe that's by design. I'll try it again!

**Comment by markmelvin** [comment]
I see... the game is just EEEEEVIIIIILLLLL! :)  Where there appears to be a gap in the obstacles isn't where you want to go (because you can't get there!) - you need to go all the way to the left or right lanes!  Closing this issue as it is working as designed.

Nice game, Weston!

**Comment by wmcnamara** [comment]
I reopened this issue just to clarify something, and give a little advice.

The method that moves the player from lane to lane is called [SmoothDamp](https://docs.unity3d.com/ScriptReference/Vector3.SmoothDamp.html). SmoothDamp doesn't immediately move the player, instead gradually moving it each frame. 

So, in short, if you time it right you can actually pass through the gap in the obstacles without switching lanes completely, which is how all the highscores are achieved.

Good luck! Happy Speedcubing! Also, thanks for playing!

It means a lot (:

**Comment by markmelvin** [comment]
Thanks, Weston! I saw that in the preview video but it is HARD! I can't imagine how anyone got past 10, but I guess it was the same for Flappy Bird. Good luck!
